### PR TITLE
Implemented CMake cache reset functionality

### PR DESCRIPTION
**Pull request by eugene-babichenko**
Implemented the functionality similar to CLions's "Reset Cmake cache". The command name is cmake_write_build_targets and it's referred as

> CMakeBuilder: Reset CMake cache

in Command Palette. Then cmake_configure can be called to get build scripts completely re-generated.

### CODE REVIEW

**Comment by rwols** [comment]
Thanks for the pull request! I want to merge this but I have a few points to address before merging:

1. I am a bit weary of the line `map(remove_file, glob.glob(os.path.join(buildFolder, '*.cmake')))`, because what if the user has its build folder as the project folder, and it so happens to have a file called FindBlaBla.cmake in its root project folder? That will get deleted accidentally. I know that everybody should do out-of-source builds, but I can't guarantee that. I think you want to delete just the cmake_install.cmake file. Maybe others too? Please rewrite it so that it is more specific exactly which cmake files should be deleted.

2. Please inherit from `sublime_plugin.WindowCommand` instead of `Default.exec.ExecCommand`.

3. There is no user feedback as to which files get deleted, but I think users should be able to see what is happening. Use `self.panel = self.window.create_output_panel('bla')` to get a panel, then show it with `self.window.run_command('show_panel', {'panel': 'output.' + 'bla'})`, and then append lines to it with `self.panel.run_command('append', {'characters': 'hello world\n'})`. Report the files that get deleted. See the [API](https://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.WindowCommand) for reference.

**Comment by eugene-babichenko** [comment]
I will also think of requesting confirmation from a user before deleting the listed files with `show_quick_panel` or something like that. It should be safer for the user to see the files to be deleted before they get deleted.

**Comment by rwols** [comment]
OK, I'll wait for the commits 💯

**Review by rwols — APPROVED** [review]

**Comment by rwols** [comment]
I incorporated the command, it's in version 0.5.0 now on package control. Thanks for your help!

**Pull request merged**
